### ISSUE TITLE
Gonna help

### ISSUE THREAD

**Issue by darkdarcool** [JBYT27/Blob-#1]
This is gonna help with the profanity check 
[here link](https://pypi.org/project/profanity-check/)

**Comment by JBYT27** [comment]
Ooohh, thanks!

**Comment by darkdarcool** [comment]
Yea, I would have made a pull request with all the curse words I know in them, but instead of that I found this. Be happy. I know a lot of bad words

**Comment by JBYT27** [comment]
LMAO. Uh, it doesn't work tho :( lol.
Importing error :(

**Comment by darkdarcool** [comment]
Did you pip install it?

**Comment by JBYT27** [comment]
Yeah, the module itself has invalid module

**Comment by darkdarcool** [comment]
hm, maybe inv me and I can try?

**Comment by JBYT27** [comment]
Ok, sure

**Comment by darkdarcool** [comment]
ok

**Comment by JBYT27** [comment]
Closing

**Comment by darkdarcool** [comment]
e
